---
deployment:
  tasks:
    - export DEPLOYPATH=/home//public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp blog-single.html $DEPLOYPATH
    - /bin/cp tentangHDI.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
    - /bin/cp -R produk $DEPLOYPATH